### ISSUE TITLE
Very heavy loadouts for RACS (1990)

### ISSUE THREAD

**Issue by Plankton555** [Sniperhid/1tac_misc#339]
It seems some of the loadouts for RACS (1990) are very heavy, and results in TMF autotest warnings. See example image below (those listed roles are not necessarily all of the problematic ones, as I had already removed some SAM/HAT groups when I took the screen shot).

After some limited testing on my own, it seems like the vest `"usm_vest_rba_lbv_rm"` (which weighs ~15 kg) might be the culprit that pushes the total weight up so much.
(For comparison, the SLA (1990) loadout uses vests that weight ~6 kg)

![racs_loadout_heavy](https://user-images.githubusercontent.com/1454000/87138140-4830cb00-c29e-11ea-8b64-b0a6524ca4e7.png)

**Comment by Plankton555** [comment]
I'm also starting to suspect that there is some bug when applying the loadout to e.g. the medic role. According to the loadout, there should be 5+15 (total 20) of "ACE_fieldDressing" in the inventory of the medic, but when I test in the editor I get 12+13+15 (total 40) of "ACE_fieldDressing".

Or could a uniform/vest contain some medical items by default, which are converted to ACE bandages when going in-game?

**Comment by Freddo3000** [comment]
The second problem is caused by the `usm_pack_m5_medic` containing equipment by default, which assingear adds on top of. You can try it in the arsenal.

**Comment by Plankton555** [comment]
Yep. Fixed the second problem by switching the backpack. Can also confirm that it didn't solve the overweight problem :P

**Comment by beaar** [comment]
Fixed
