### ISSUE TITLE
Autotest incorrectly displaying all roles as "Heavy role"

### ISSUE THREAD

**Issue by Toiton** [Sniperhid/1tac_misc#342]
Autotest claims that all roles are too heavy, regardless of actual weight. I checked several missions and they all had the same problem.

![image](https://user-images.githubusercontent.com/18167380/88459675-03f11d80-ce8f-11ea-958b-342bcb6394d8.png)

**Comment by headswe** [comment]
This is the wrong repo.
https://github.com/TMF3/TMF/issues
