### ISSUE TITLE
FEATURE REQUEST: Grass Cutter Self-Interact

### ISSUE THREAD

**Issue by HindsFiveSeven** [Sniperhid/1tac_misc#343]
Problem: 99% of the time when one uses their bipod in the prone, there will be tall grass completely and totally inhibiting their view.

Solution: ACE self-interact to remove grass in a radius by spawning a grass cutter in to a nearby location the player is looking at. In reality, a person could easily tear, smash, or otherwise permanently "deal with" tall grass blocking their field of fire just by using their hands. A tool would not necessarily be required.

There is a mod which adds this functionality to the entrenching tool, but the entrenching tool is not currently in most loadouts and would thus need to be manually added to loadouts for it to become standard. The entrenching tool also weighs 1 pound, which is not much, but it's still perhaps not worth the inventory space/weight just to be able to remove grass.

**Comment by headswe** [comment]
H0t

**Comment by beaar** [comment]
added under self -> equipment interact
